- name: Demonstrates conditional installation
  hosts: all
  vars:
    - greeting_msg: DevOps
    - automation_tool: Ansible
    - provisioner_tool: Docker
  tasks:
    - name: Install nginx web server in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      apt: name=nginx state=latest update_cache=yes

    - name: Install EPEL(Extra Package for Enterprise Linux) in CentOS
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=epel-release state=latest

    - name: Install nginx web server in CentOS
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=nginx state=latest

    - name: Configure nginx web server in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      copy: src=default dest=/etc/nginx/sites-available/default
      notify:
         - Restart nginx web server

    - name: Configure nginx web server in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
      notify:
         - Restart nginx web server

    - name: Create the updated web root folder
      file: path=/var/html state=directory mode=0777

    - name: Deploy web page in nginx web server
      template: src=index.html.j2 dest=/var/html/index.html

  handlers:
    - name: Restart nginx web server
      command: service nginx restart
      #service: name=nginx state=restarted - Can't be used as there is a documented bug
